### ISSUE TITLE
the performance is not so good as expected

### ISSUE THREAD

**Issue by thunder95** [JimLee1996/AVSS2019#10]
I tried demo with my webcam or some video clips.
even one single person or much tiny body movement could cause "violent" label.
Whats the problem for that? can this repo  be used in online infering?

**Comment by JimLee1996** [comment]
It's not a good idea to just download the model and run it directly without any change.
Maybe the scene where you use it is varied from the train data. And please consider adding some new samples, such as bad cases、positive cases, then fine-tune and re-evaluate the model.

P.S. Tesla auto-drive has a powerful detection model fed by large amount of data, however also fails and causes accident in some cases.
